language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: nightly
    # minimum rustc version
    - rust: 1.29.0
      script: cargo build

  allow_failures:
    - rust: nightly

script:
  - cargo check --no-default-features
  - cargo test --lib --no-default-features
  - cargo test --tests --no-default-features
  - cargo test
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then cd test_suite && cargo test; fi

notifications:
  email:
    on_success: never
